name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Kodları indir
      uses: actions/checkout@v2

    - name: JDK yükle
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Gradle Wrapper'a izin ver
      run: chmod +x ./gradlew

    - name: APK Derle
      run: ./gradlew assembleDebug

    - name: APK'yı Artifacts olarak kaydet
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
